const mongoose=require('mongoose')
const Schema=mongoose.Schema({
    name:{
        type:String,
        required:true,
        maxLength:150,
        trim:true
    },
    Description:{
        type:String,
        maxLength:1000,
        require:true,
        trim:true
       },
       Price:{
           type:Number,
           require:true
       },
       Quantity:{
           require:true,
           type:Number
       }
       ,
       Solde:{
           type:Number
       }
       ,
       Photo:{
           data:Buffer,
       contentType:String
   },
       
       category:{
           type:ObjectId,
           ref:'Category', 
           require:true
       },
       Shipping:{
           type:Boolean,
           require:false,
           default:false
       },
       IsInSTock:{
        type:Boolean,
           require:false,
           default:true
       }
},{timestamps:true})
module.exports=mongoose.model('Product',productShema);
